# Generated by Django 4.1 on 2023-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logAuth', '0007_alter_profil_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='desc',
            field=models.TextField(default="Salut, j'utilise WatAdd...", max_length=800),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(default='/media/aei.png', upload_to='photos'),
        ),
    ]
